### ISSUE TITLE
Create a containerized version (e.g., Docker image) with all tools installed

### ISSUE THREAD

**Issue by dcwalk** [edgi-govdata-archiving/harvesting-tools#19]
Feedback from @rpattcorner event:
> a prebuilt toolkit with all major tools installed, as a docker

**Comment by rpattcorner** [comment]
Version 0.1 is available for test on the [rpattcorner fork](https://github.com/rpattcorner/harvesting-tools/tree/initial_docker/docker) and [dockerhub](https://hub.docker.com/r/rpattcorner/datarescue-tools/).  Contains aws tools, epa-envirofacts scraper and python-scraper (with both beautiful soup and selenium+phantomjs working)

**Comment by dcwalk** [comment]
Closing as this has been superseded by work on Data Together: https://github.com/datatogether/archivertools
