### ISSUE TITLE
AWS toolchain integration

### ISSUE THREAD

**Issue by waflores** [edgi-govdata-archiving/harvesting-tools#24]
The current tool chain for data harvesting doesn't have any hooks for working with AWS. For instance, running this tooling on an EC2 instance & plugging the data into S3 automagically.

**Comment by dcwalk** [comment]
Definitely a good point to consider! I'm going to close this however as this work has been superseded by https://github.com/datatogether/archivertools and this repo is no longer under active development.

While we aren't integrating into AWS, we have toolchain integration, quicker dev environment setup and more
