### ISSUE TITLE
What is the status of check-ia.py

### ISSUE THREAD

**Issue by titaniumbones** [edgi-govdata-archiving/harvesting-tools#3]
`check-ia.py` is currently orphaned in the workflow repo (once we move these tools here, no other code will live in the repo). What should we do with it.

At the very least we should indicate that it is a tool for *checking seeds,* not for harvesting.

**Comment by dcwalk** [comment]
A lot of harvesters used it at the A2 event, I think in a sense it is a 'supplementary tool', rather than one for harvesting. It also supports (bulk) _research_ more than individual seeding

**Comment by titaniumbones** [comment]
So should I add it here?

**Comment by mhucka** [comment]
Please feel free to relocate it wherever it makes the most sense (or tell me where to put it).

**Comment by dcwalk** [comment]
I think so, also, what about the recently merged in example? [watir.rb](https://github.com/datarefugephilly/workflow/tree/master/harvesting-toolkit/tools/example-hacks)

I want that stuff, and a chunk of the harvesting toolkit readme here. Does that make sense or am I interpreting this wrong?

**Comment by titaniumbones** [comment]
totally makes sense, probably needs to be cleaned up a little or at
least some particulars noted in `README`.

dcwalk <notifications@github.com> writes:

> I think so, also, what about the recently merged in example? [watir.rb](https://github.com/datarefugephilly/workflow/tree/master/harvesting-toolkit/tools/example-hacks)
>
> I want that stuff, and a chunk of the harvesting toolkit readme here. Does that make sense or am I interpreting this wrong? 


--

**Comment by titaniumbones** [comment]
Added to this repo/ very slightly modified READMe. Thx @mhucka!
