### ISSUE TITLE
mandate paths.txt and urls.txt in tools?

### ISSUE THREAD

**Issue by titaniumbones** [edgi-govdata-archiving/harvesting-tools#5]
Do we want to require paths.txt and urls.txt in these tools? that would mean standardizing them all a bit better.

**Comment by mhucka** [comment]
Um, I feel stupid to have to ask, but I think I'm not following here. Is your point about the names of the files (i.e., to standardize on the names `paths.txt` and `urls.txt`) or is the point something else?

**Comment by titaniumbones** [comment]
sorry, comes from another issue I think.  Question was: de we require that the tools in the repo (not check-ia actually, but the other tools, which harvest web pages) make use of `path.txt` and `urts.txt` the wat that `wget-loop` does?  If we had such a requirement ,the pipeline app @b5 and @danielballan are building could prepopulate those files.

**Comment by dcwalk** [comment]
I'm closing this as I think these implementation questions will move to https://github.com/datatogether/archivertools. Feel free to reopen if you feel like this needs to be addressed here
