### ISSUE TITLE
Tools for harvesting ArcGIS REST endpoints?

### ISSUE THREAD

**Issue by hampelm** [edgi-govdata-archiving/harvesting-tools#8]
Do we have a procedure for pulling down whole ESRI REST endpoints? Eg https://map11.epa.gov/arcgis/rest/services. 

OpenAddresses uses this useful scraper to get individual datasets from mapservers, imageservers, and featureservers: https://github.com/openaddresses/esri-dump

cc @louh

**Comment by dcwalk** [comment]
This is definitely a good point to consider! I'm going to close this however as this work has been superseded by https://github.com/datatogether/archivertools 

I've raised the question there how to account for asks like this as we move forward :)
